image: node

stages:          # List of stages for jobs, and their order of execution
  - test

eslint:   # This job runs in the test stage.
  stage: test
  script:
    - npm i eslint
    - npm -g i eslint-cli
    - eslint "src/**"
