image: node

stages:          # List of stages for jobs, and their order of execution
  - test

frontend-eslint:   # This job runs in the test stage.
  stage: test
  script:
    - cd frontend
    - npm i eslint
    - npm -g i eslint-cli
    - npx eslint --ext js,jsx src

backend-eslint:   # This job runs in the test stage.
  stage: test
  script:
    - cd backend
    - npm i eslint
    - npm -g i eslint-cli
    - npx eslint --ext js,jsx src